build_image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH
  rules:
    - if: $CI_COMMIT_BRANCH

pages:
  script:
    - hugo --minify -e gl-pages -s website -d ../public
  artifacts:
    paths:
      - public
  only:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  except:
    refs:
      - main

aws:
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
  image: 
    name: $CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH
    entrypoint: [""]
  script:
    - hugo --minify -e s3 -s website
    - echo AWS_ACCESS_KEY_ID
    - hugo deploy --force --maxDeletes -1 --invalidateCDN -e s3 -s website
  only:
    refs:
      - main
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
